services:
  go-fast-chat-database:
    image: postgres:alpine
    environment:
      POSTGRES_DB: go-fast-chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  
  go-fast-chat-cache:
    image: redis:alpine
    ports:
      - "6379:6379"
  